number = input("Enter a number: ")
number1 = int(number)

print(f"One times {number1} is {number1*1}")
print(f"Two times {number1} is {number1*2}")
print(f"Three times {number1} is {number1*3}")
print(f"Four times {number1} is {number1*4}")
print(f"Five times {number1} is {number1*5}")
print(f"Six times {number1} is {number1*6}")
print(f"Seven times {number1} is {number1*7}")
print(f"Eight times {number1} is {number1*8}")
print(f"Nine times {number1} is {number1*9}")
print(f"Ten times {number1} is {number1*10}")
print(f"Eleven times {number1} is {number1*11}")
print(f"Twelve times {number1} is {number1*12}")