number = input("Enter a number: ")
number1 = int(number)

print(f"{number1} to the power of 1 is {number1**1}")
print(f"{number1} to the power of 2 is {number1**2}")
print(f"{number1} to the power of 3 is {number1**3}")
print(f"{number1} to the power of 4 is {number1**4}")
print(f"{number1} to the power of 5 is {number1**5}")
print(f"{number1} to the power of 6 is {number1**6}")
print(f"{number1} to the power of 7 is {number1**7}")
print(f"{number1} to the power of 8 is {number1**8}")
print(f"{number1} to the power of 9 is {number1**9}")
print(f"{number1} to the power of 10 is {number1**10}")
print(f"{number1} to the power of 11 is {number1**11}")
print(f"{number1} to the power of 12 is {number1**12}")